import os

from pomodoro_timer.configs.main_configs import SOUNDS_DIR_SESSION_START, SOUNDS_DIR_BREAK_START, \
    SOUNDS_PARAM_SOUND_ON, SOUNDS_PARAM_SESSION_START, SOUNDS_PARAM_BREAK_START

DEFAULT_SOUNDS_PARAMS = {
    SOUNDS_PARAM_BREAK_START: os.listdir(SOUNDS_DIR_BREAK_START)[0],
    SOUNDS_PARAM_SESSION_START: os.listdir(SOUNDS_DIR_SESSION_START)[0],
    SOUNDS_PARAM_SOUND_ON: True
}
