TIMER_PARAM_NUM_POMODOROS = "number_of_pomodoros"
TIMER_PARAM_SESSION_LENGTH = "session_length"
TIMER_PARAM_BREAK_LENGTH = "break_length"
TIMER_PARAM_LONG_BREAK_LENGTH = "long_break_length"


DEFAULT_TIMER_PARAMS = {
    TIMER_PARAM_SESSION_LENGTH: 25,
    TIMER_PARAM_BREAK_LENGTH: 5,
    TIMER_PARAM_LONG_BREAK_LENGTH: 20,
    TIMER_PARAM_NUM_POMODOROS: 4,
}

SECOND = 1000
MINUTE = 60

STATE_IDLE = 0
STATE_RUN = 1
STATE_BREAK = -1
STATE_LONG_BREAK = -2
STATE_PAUSED = -3


TIMER_PARAM_KEYS = {
    STATE_IDLE: "",
    STATE_RUN: TIMER_PARAM_SESSION_LENGTH,
    STATE_BREAK: TIMER_PARAM_BREAK_LENGTH,
    STATE_LONG_BREAK: TIMER_PARAM_LONG_BREAK_LENGTH
}

